version: '2'
services:
    mygatewayapp-app:
        image: mygatewayapp
        external_links:
            - mygatewayapp-postgresql:postgresql
            # Uncomment to have Cassandra working with the gateway
            # - mygatewayapp-cassandra:cassandra
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mygatewayapp
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
        ports:
            - 8080:8080
    mygatewayapp-postgresql:
        extends:
            file: postgresql.yml
            service: mygatewayapp-postgresql
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra-cluster.yml
        #     service: mygatewayapp-cassandra
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
